"""Changed county codes

Revision ID: 12245a1d94c2
Revises: dc8e133d9cd6
Create Date: 2024-01-01 21:51:22.846625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from src.operations.choices.symbols import SYMBOLS
from src.operations.choices.categories import CATEGORIES


# revision identifiers, used by Alembic.
revision: str = '12245a1d94c2'
down_revision: Union[str, None] = 'dc8e133d9cd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_table_email', table_name='user_table')
    op.drop_table('user_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_table_pkey'),
    sa.UniqueConstraint('username', name='user_table_username_key')
    )
    op.create_index('ix_user_table_email', 'user_table', ['email'], unique=False)
    # ### end Alembic commands ###
