"""Initial revision

Revision ID: f0991a08cdc2
Revises: 
Create Date: 2023-10-01 16:03:27.599634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from src.operations.choices.symbols import SYMBOLS
from src.operations.choices.categories import CATEGORIES

# revision identifiers, used by Alembic.
revision: str = 'f0991a08cdc2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category', sqlalchemy_utils.types.choice.ChoiceType(CATEGORIES), nullable=True))
    op.drop_constraint('product_category_id_fkey', 'product', type_='foreignkey')
    op.drop_column('product', 'category_id')
    op.drop_table('category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('product_category_id_fkey', 'product', 'category', ['category_id'], ['id'],
                          ondelete='CASCADE')
    op.drop_column('product', 'category')
    op.create_table('category',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='category_pkey')
                    )
    # ### end Alembic commands ###
