"""discount-% to discount

Revision ID: c70bbc4b43bb
Revises: f0991a08cdc2
Create Date: 2023-10-02 15:08:41.784167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from src.operations.choices.symbols import SYMBOLS
from src.operations.choices.categories import CATEGORIES


# revision identifiers, used by Alembic.
revision: str = 'c70bbc4b43bb'
down_revision: Union[str, None] = 'f0991a08cdc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('discount', sa.Integer(), nullable=True))
    op.drop_column('product', 'discount-%')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('discount-%', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('product', 'discount')
    # ### end Alembic commands ###
