"""empty message

Revision ID: dc8e133d9cd6
Revises: c70bbc4b43bb
Create Date: 2023-10-08 13:47:45.694259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from src.operations.choices.symbols import SYMBOLS
from src.operations.choices.categories import CATEGORIES


# revision identifiers, used by Alembic.
revision: str = 'dc8e133d9cd6'
down_revision: Union[str, None] = 'c70bbc4b43bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rating_user_id_fkey', 'rating', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('rating_user_id_fkey', 'rating', 'user_table', ['user_id'], ['id'])
    # ### end Alembic commands ###
